services:
  db:
    image: postgres:13
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todos_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: web
    depends_on:
      db:
        condition: service_healthy
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app:create_app
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todos_db
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app

volumes:
  postgres_data: