version: '3.8'

services:
  db:
    image: postgres:13
    container_name: db  
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todos_db"]  
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - app-network

  web:
    build: .
    container_name: web
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app:create_app
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/todos_db
    volumes:
      - ./app/templates:/app/app/templates
      - ./app/static:/app/app/static
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    user: "1000:1000"

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge